// Generated by CoffeeScript 1.6.3
(function() {
  var Spine;

  Spine = this.Spine || require('spine');

  Spine.Model.Local = {
    extended: function() {
      this.change(this.saveLocal);
      return this.fetch(this.loadLocal);
    },
    saveLocal: function() {
      var result;
      result = JSON.stringify(this);
      return localStorage[this.className] = result;
    },
    loadLocal: function(options) {
      var result;
      if (options == null) {
        options = {};
      }
      if (!options.hasOwnProperty('clear')) {
        options.clear = true;
      }
      result = localStorage[this.className];
      return this.refresh(result || [], options);
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Spine.Model.Local;
  }

}).call(this);

/*
//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibG9jYWwuanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbInNyYy9sb2NhbC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBO0NBQUEsSUFBQSxDQUFBOztDQUFBLENBQUEsQ0FBUSxDQUFDLENBQVQsRUFBa0I7O0NBQWxCLENBRUEsQ0FDRSxFQURHO0NBQ0gsQ0FBVSxDQUFBLENBQVYsSUFBQSxDQUFVO0NBQ1IsR0FBQyxFQUFELEdBQUE7Q0FDQyxHQUFBLENBQUQsSUFBQSxJQUFBO0NBRkYsSUFBVTtDQUFWLENBSVcsQ0FBQSxDQUFYLEtBQUE7Q0FDRSxLQUFBLElBQUE7Q0FBQSxFQUFTLENBQUksRUFBYixHQUFTO0NBQ0ksRUFBYyxDQUFiLEtBQUQsR0FBQSxDQUFiO0NBTkYsSUFJVztDQUpYLENBUVcsQ0FBQSxDQUFYLEdBQVcsRUFBWDtDQUNFLEtBQUEsSUFBQTs7R0FEb0IsS0FBVjtRQUNWO0FBQTRCLENBQTVCLEdBQUEsRUFBQSxDQUFtQyxPQUFQO0NBQTVCLEVBQWdCLENBQWhCLENBQUEsRUFBTyxDQUFQO1FBQUE7Q0FBQSxFQUNTLENBQWMsRUFBdkIsR0FBc0IsR0FBQTtDQUNyQixDQUFELEVBQUMsRUFBUSxDQUFULE1BQUE7Q0FYRixJQVFXO0NBWGIsR0FBQTs7O0NBZ0JRLEVBQVUsQ0FBbEIsQ0FBdUIsQ0FBakIsQ0FBTjtJQWhCQTtDQUFBIiwic291cmNlc0NvbnRlbnQiOlsiU3BpbmUgPSBAU3BpbmUgb3IgcmVxdWlyZSgnc3BpbmUnKVxuXG5TcGluZS5Nb2RlbC5Mb2NhbCA9XG4gIGV4dGVuZGVkOiAtPlxuICAgIEBjaGFuZ2UgQHNhdmVMb2NhbFxuICAgIEBmZXRjaCBAbG9hZExvY2FsXG5cbiAgc2F2ZUxvY2FsOiAtPlxuICAgIHJlc3VsdCA9IEpTT04uc3RyaW5naWZ5KEApXG4gICAgbG9jYWxTdG9yYWdlW0BjbGFzc05hbWVdID0gcmVzdWx0XG5cbiAgbG9hZExvY2FsOiAob3B0aW9ucyA9IHt9KS0+XG4gICAgb3B0aW9ucy5jbGVhciA9IHRydWUgdW5sZXNzIG9wdGlvbnMuaGFzT3duUHJvcGVydHkoJ2NsZWFyJylcbiAgICByZXN1bHQgPSBsb2NhbFN0b3JhZ2VbQGNsYXNzTmFtZV1cbiAgICBAcmVmcmVzaChyZXN1bHQgb3IgW10sIG9wdGlvbnMpXG5cbm1vZHVsZT8uZXhwb3J0cyA9IFNwaW5lLk1vZGVsLkxvY2FsIl19

*/
